version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=hlanz
      - MONGO_INITDB_DATABASE=db_apis
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/db_apis --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://admin:hlanz@mongodb:27017/db_apis?authSource=admin
      - JWT_SECRET=your_jwt_secret_key
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm run seed && npm start"

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=hlanz
      - ME_CONFIG_MONGODB_URL=mongodb://admin:hlanz@mongodb:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=hlanz
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:
